### PR TITLE
Make Ctrl-C nicer

### LINKED ISSUE #3: Make Ctrl+C nicer
Pressing Ctrl+C results in:

``` sh
$ cargo run --example list
     Running `target/debug/examples/list`
[?] Choose an option:
    An option
  > Another option
    Something else?thread 'main' panicked at 'Ctrl-C', src/list.rs:60
                                                                     note: Run with `RUST_BACKTRACE=1` for a backtrace.
                                                                                                                       error: Process didn't exit successfully: `target/debug/examples/list` (exit code: 101)
```

This is pretty confusing. Also, this does not reset the cursor – it stays hidden!

### PR DESCRIPTION
**Pull request by killercup**
Fixes #3 

Currently based on #1, just read the last commit. (Just ping me and I can rebase this)

### CODE REVIEW

**Comment by Munksgaard** [comment]
I'm not convinced that either panicking or exiting is the best option here. If we want inquirer-rs to be a nice and usable library, it shouldn't arbitrarily shut down the users programs. I think that should be up to the user.

I believe a more long-term solution would be to return an Error type. My original idea was to make `list` return `Option<T>` instead, and let `None` indicate "lack of choice" aka pressing ctrl-c, but now I guess we can just add another error type to `Error`?

What does Inquirer.js do in the case that ctrl-c is pressed?

**Comment by killercup** [comment]
You're right, an `Error::UserAborted` or something like that is much nicer, but requires the library user to deal with this (which is okay for me). I'll change the PR to do that.

> What does Inquirer.js do in the case that ctrl-c is pressed?

No idea, I'd expect it to either throw a custom error (that exits the program when you don't catch it) or don't handle it at all and do whatever node does when you press Ctrl-C.

**Comment by Munksgaard** [comment]
:+1:

**Comment by Munksgaard** [comment]
Could I ask you to fast-forward this branch? Thanks!

**Comment by killercup** [comment]
Resolved conflicts and rebased on current master. (Also sneaked in a change to use `.get`!)

**Pull request merged**
